name: publish
on: [push]
env:
  TEST_TAG: ghcr.io/bgu035/publish-to-gcr:test
  LATEST_TAG: ghcr.io/bgu035/publish-to-gcr:latest
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker build
      uses: docker/build-push-action@v3
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}
        
       
    - name: Docker push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.LATEST_TAG }}

