name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker build
        uses:docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
        
    - name: Run the hello-docker Docker image
      run: |
       docker run ghcr.io/bgu035/publish-to-gcr:latest
       
    - name: Docker push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}

